package model;
// Generated Nov 6, 2017 3:29:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private Post post;
     private Users users;
     private Date dateCreated;
     private String content;

    public Comments() {
    }

    public Comments(Post post, Users users, Date dateCreated, String content) {
       this.post = post;
       this.users = users;
       this.dateCreated = dateCreated;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


