package model;
// Generated Nov 6, 2017 3:29:36 PM by Hibernate Tools 4.3.1



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String title;
     private String content;

    public Messages() {
    }

    public Messages(Users users, String title, String content) {
       this.users = users;
       this.title = title;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


