package model;
// Generated Nov 6, 2017 3:29:36 PM by Hibernate Tools 4.3.1



/**
 * PostTags generated by hbm2java
 */
public class PostTags  implements java.io.Serializable {


     private Integer id;
     private Post post;
     private Tags tags;

    public PostTags() {
    }

    public PostTags(Post post, Tags tags) {
       this.post = post;
       this.tags = tags;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public Tags getTags() {
        return this.tags;
    }
    
    public void setTags(Tags tags) {
        this.tags = tags;
    }




}


