package model;
// Generated Nov 6, 2017 3:29:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String title;
     private String description;
     private String content;
     private Integer status;
     private Date dateModified;
     private Date dateCreated;
     private Set postTagses = new HashSet(0);
     private Set commentses = new HashSet(0);

    public Post() {
    }

    public Post(Users users, String title, String description, String content, Integer status, Date dateModified, Date dateCreated, Set postTagses, Set commentses) {
       this.users = users;
       this.title = title;
       this.description = description;
       this.content = content;
       this.status = status;
       this.dateModified = dateModified;
       this.dateCreated = dateCreated;
       this.postTagses = postTagses;
       this.commentses = commentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set getPostTagses() {
        return this.postTagses;
    }
    
    public void setPostTagses(Set postTagses) {
        this.postTagses = postTagses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


