package model;
// Generated Nov 6, 2017 3:29:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer number;
     private Set postTagses = new HashSet(0);

    public Tags() {
    }

    public Tags(String name, Integer number, Set postTagses) {
       this.name = name;
       this.number = number;
       this.postTagses = postTagses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Set getPostTagses() {
        return this.postTagses;
    }
    
    public void setPostTagses(Set postTagses) {
        this.postTagses = postTagses;
    }




}


